### ISSUE TITLE
Who Covers What?

### ISSUE THREAD

**Issue by bradgreen3** [pemj/cis590#15]
I'm very new to GitHub, so forgive me if I do anything stupid on here, but it seems like using the issues section is the best way to communicate with everyone, so I'm going to ask here: who is covering what topics? I'm completely indifferent to what I cover--just let me know what, and I'll get it done. 

-Brad

**Comment by pemj** [comment]
The issue tracker is a sort-of way to figure out what we're each covering.  The paper is due Monday of finals week, but our presentation is scheduled for Monday of dead week, so I think we're going to be focusing on that.  I'll send out an email later today, summarizing the meeting we had after class, and some stuff to think about to prepare for our next meeting, which we've tentatively planned for Wednesday after class.

As for the paper, I think we'll have a clearer idea of where we're going with that by the end of our meeting on Wednesday, and we can update the issue tracker accordingly be assigning ourselves to particular sections.
