### ISSUE TITLE
Present Scenario

### ISSUE THREAD

**Issue by pemj** [pemj/cis590#17]
Section needs to be written

**Comment by gsondur** [comment]
written out a first draft.  Don't have many citations for this. Also how do I compile it on my machine?

**Comment by pemj** [comment]
I imagine he'll be fine without tooo many citations.  I'm not sure how to compile it on your machine.  I've got the TeXLive package installed, and an emacs plugin that calls the `pdflatex,` command on main.tex.  So, uh, whatever is the equivalent to that on your machine.
