### ISSUE TITLE
Value System: Economic consequences

### ISSUE THREAD

**Issue by pemj** [pemj/cis590#25]

**Comment by gsondur** [comment]
Do you guys want me to add stuff to the values system? for the moment I have only added what was written under the main idea on the google doc. I am assuming Elizabeth still wants to write on the autonomy of self?

**Comment by pemj** [comment]
I can go for economy when I get out in an hour or so.  You may want to do
the other thing though, don't know if Elizabeth's got time

**Comment by gsondur** [comment]
Ok cool, I'll elaborate on the various parts and what elements they constitute. I was asking because she had expressed some interest in that portion. I'll go ahead and add some things.

**Comment by gsondur** [comment]
I've added stuff on the first two points of our value system, if someone could give it a quick look and let me know of any changes required

**Comment by pemj** [comment]
I'll look at it in a sec.  Just added outline to values, gonna try to bang some of that out real quick.

**Comment by gsondur** [comment]
you might want to pull that before you change anything
